### ISSUE TITLE
Firefox (35+) sharing service

### ISSUE THREAD

**Issue by BengaloBongali** [jaywink/diaspora-advanced-sharer#6]
Is there any chance of making this a real Firefox service like it's used for Facebook, Twitter,... as of Firefox 35 via the new share button? That would be great!

**Comment by BengaloBongali** [comment]
https://activations.cdn.mozilla.net/

**Comment by jaywink** [comment]
Yes! This has come available now via the Advanced Sharer for diaspora - see here: http://sharetodiaspora.github.io/about/
