### ISSUE TITLE
¿question?

### ISSUE THREAD

**Issue by victorhck** [jaywink/diaspora-advanced-sharer#7]
How to change to a new pod? I'm doing a migration to a new pod, but I can't find the way to change the link to my new pod.
Do I have to unistall, and install again? Edit some config file?
BTW Great tool!
##

**Comment by jaywink** [comment]
Try visiting this link: http://sharetodiaspora.github.io/?url=foobar&redirect=false and then click `Forget my choice` from the bottom. The add-on uses this service so clearing this cookie will help.

I'll leave this open until I put this in the readme of the add-on, thanks for reporting :)

**Comment by victorhck** [comment]
Thanks!
Yesterday I found the solution... But I can't find the link!! :(
Was a tip where the user had to add a parameter and ready to start sharing in another pod...

**Comment by jaywink** [comment]
Sorry, did the link above work for you?

**Comment by victorhck** [comment]
yep, was useful too!
Thnx!!
