### ISSUE TITLE
Button to share not visible in toolbar in Firefox 40

### ISSUE THREAD

**Issue by jaywink** [jaywink/diaspora-advanced-sharer#8]
##

**Comment by magicvince** [comment]
not visible in ff45 with Linux Mint Debian Edition

**Comment by jaywink** [comment]
This add-on is basically legacy and will not be updated. The new Firefox requires rewriting add-on's as WebExtensions anyway, so the problem is larger.

I recommend using the native Firefox share feature, which has integration to the diaspora sharing service, if on FF56 or below. If on FF57 or above, [this extension](https://addons.mozilla.org/en-US/firefox/addon/share-backported/) backports the share feature which was removed in FF57.

It basically does the same thing as this add-on did.
