### ISSUE TITLE
Firefox for Android support

### ISSUE THREAD

**Issue by Mikaela** [jaywink/diaspora-advanced-sharer#9]
It would be nice if this extension supported Firefox for Android.

Currently I only share links on Diaspora* when I am on laptop as there is no easy way to share to Diaspora from mobile.
##

**Comment by jaywink** [comment]
This add-on will not be updated any more as it's not compatible with the modern Firefox versions.

For mobile Firefox, the bookmarklet (diaspora native or sharing service) actually works really well, I use it daily.

Thanks for raising anyway!
